// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyDUyymd8Lq13JhOLa-lztI0iAfz00dkur8',
  appId: '1:400168708988:web:e8df92090c783f23fd12f9',
  messagingSenderId: '400168708988',
  projectId: 'lentera-21607',
  authDomain: 'lentera-21607.firebaseapp.com',

  databaseURL:
      'https://lentera-21607-default-rtdb.asia-southeast1.firebasedatabase.app',

  storageBucket: 'lentera-21607.firebasestorage.app',
  measurementId: 'G-XX6LYZX1VG',
);

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpWGYrgFz3gHclU8c26_BBcWs_sCF0rc',
    appId: '1:400168708988:android:a04b66d39052a001fd12f9',
    messagingSenderId: '400168708988',
    projectId: 'lentera-21607',
    storageBucket: 'lentera-21607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxoB0NLbScbFl4LrGs5IY7iShJkXoUNw',
    appId: '1:400168708988:ios:e669f4d02ffd1ebcfd12f9',
    messagingSenderId: '400168708988',
    projectId: 'lentera-21607',
    storageBucket: 'lentera-21607.firebasestorage.app',
    iosBundleId: 'com.example.lenteraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxoB0NLbScbFl4LrGs5IY7iShJkXoUNw',
    appId: '1:400168708988:ios:e669f4d02ffd1ebcfd12f9',
    messagingSenderId: '400168708988',
    projectId: 'lentera-21607',
    storageBucket: 'lentera-21607.firebasestorage.app',
    iosBundleId: 'com.example.lenteraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUyymd8Lq13JhOLa-lztI0iAfz00dkur8',
    appId: '1:400168708988:web:e91b9aecc0c27a00fd12f9',
    messagingSenderId: '400168708988',
    projectId: 'lentera-21607',
    authDomain: 'lentera-21607.firebaseapp.com',
    storageBucket: 'lentera-21607.firebasestorage.app',
    measurementId: 'G-8ZJV45ZK7G',
  );
}
